Handle exceptions when no language features detected
mabruras/sqapi-plugins pull request #15
Opened 2019-10-04 06:36 UTC by mariufa

2019-10-07 07:47 UTC, mabruras requested changes

2019-10-07 07:47 UTC, mabruras commented on languages/__init__.py
> +            return
Is this necessary, if `detect_language` raises exception when no language features are detected?

2019-10-07 07:47 UTC, mabruras commented on languages/__init__.py
> +    MAX_BYTE_SIZE_TO_READ = 10000
Maybe move this constant to module level, or rename to a lower case variable.

2019-10-07 07:47 UTC, mabruras commented on languages/__init__.py
> +        stringData = data.read(MAX_BYTE_SIZE_TO_READ).decode()
Please use naming convention according to [`PEP8` - Function and Variable Names](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names)

2019-10-07 07:47 UTC, mabruras commented on languages/__init__.py
>      lang = metadata.get('lang', None) or metadata.get('language', None)
An alternative to hard coding in `lang` and `language` could be to fetch the potential name from the configuration. Like creating a tag in the `custom` part of the plugin configuration, as in these examples:
* Faces plugin: [config](https://github.com/mabruras/sqapi-plugins/blob/master/faces/config.yml#L18) - [usage](https://github.com/mabruras/sqapi-plugins/blob/master/faces/__init__.py#L23-L24)
* Thumbnails plugin: [usage](https://github.com/mabruras/sqapi-plugins/blob/master/thumbnails/__init__.py#L21-L22)

2019-11-26 15:56 UTC, mariufa commented
Also testet a file to check for language in metadata

2019-12-01 13:50 UTC, mabruras approved these changes

2019-12-01 13:51 UTC, merged